sudo: required
dist: trusty

language: haxe

os:
  - linux
  
haxe:
  - "3.2.1"
  - "3.4.0"
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix js
